### ISSUE TITLE
Add FreeRTOS as dependency

### ISSUE THREAD

**Issue by mfs12** [Duet3D/PanelDueFirmware#107]
FreeRTOS is a dependency of RRFLibraries so it should be added as dependency.

A table with dependencies like in reprap firmware would be handy.

Refert to https://github.com/Duet3D/RepRapFirmware/wiki/Building-RepRapFirmware for examples.

**Comment by dc42** [comment]
PanelDue only uses configurations of RRFLibraries that do not use FreeRTOS, therefore FreeRTOS is not needed in the workspace when building PanelDueFirmware.

**Comment by mfs12** [comment]
Yes, this is true, although eclipse throws a warning that it could not find some FreeRTOS paths during the build.
