### ISSUE TITLE
Display in Portrait Mode. 

### ISSUE THREAD

**Issue by harlodx** [Duet3D/PanelDueFirmware#154]
### Is your feature request related to a problem? Please describe.

So far as I have been able to find there is no option for using the display in portrait mode. It seems like the larger 7 inch screen might be well suited to being used in this orientation. 

### Describe the solution you propose.

I would suggest providing an option in settings to rotate the screen by ninety degree increments and having the system adjust the layout accordingly to fit in portrait/landscape mode as required.

### Provide any additional context or information.

I can see that there is a similar request for this feature that has been closed previously, but can't seem to find any detail on progress.

**Comment by mfs12** [comment]
Hey @harlodx, thanks for suggesting this feature. It was internally discussed but the effort is too big at the moment with current software.

This means as long as we don't do an overhaul of the UI Kit or move to another hardware this is not going to happen.
