### ISSUE TITLE
Activate screen when a new message arrives although screensaver is active

### ISSUE THREAD

**Issue by mfs12** [Duet3D/PanelDueFirmware#167]
### Description

Adapt the behavior in the following situation:

- screensaver is active and LCD is dimmed
- message arrives M291 S0, S1, S2 or S3 arrrives
- screensaver is deactivated and LCD is undimmed
- message is displayed
- if message with no user action is displayed (M291 S1 or S2) screensaver is activated and LCD is dimmed after inactivatiy timeout
- if message with user action is displayed (M291 S3 or S4) screensaver and LCD dimming stays deactivated indefinitely until the user closes the message

**Comment by dc42** [comment]
Yes I agree with that. In the final case, if the message is cancelled by RRF (e.g. because it has been acknowledged in DWC or the Duet rebooted), then the dimming and screensaver timeout should start up again from that point.
