### ISSUE TITLE
Macros buttons overlaying temperatures

### ISSUE THREAD

**Issue by timmit99** [Duet3D/PanelDueFirmware#22]
I have run into a bug/issue with the latest PanelDue firmweare 1.20beta4 (File Name "PanelDue-v3-7.0.bin") 

"The first 4 macros are displayed on the Control page unless there are too many tools configured to leave room"

We are using the PanelDue on a machine where the first tool has 5 heaters, the second tool has one heater and the third tool has one heater. The macro buttons (as stated above) overlaps the temperature buttons for our other tools. The firmware seems to note that there are only 3 tools so it thinks it should be able to display the macros without overlapping anything. However, our 7 heaters are in the way and the buttons conflict. 

![28879880_10156172029233491_591222193_o](https://user-images.githubusercontent.com/8399317/37171631-795f7960-22dc-11e8-960e-b9f983e26b6b.jpg)

Also, because our tools have multiple heaters, the tool icon in the top row no longer correspond to the proper heaters below it. ( I.E. Tool2 icon is above a heater that is associated with Tool1) 
Below is a lovely representation of how the layout theoretically should.
![actualsetup](https://user-images.githubusercontent.com/8399317/37172021-a6e6aa92-22dd-11e8-9880-3092f29215c7.jpg)

**Comment by timmit99** [comment]
Could the macro button display be a toggle-able setting in "Setup" to allow users to turn it on or off?

**Comment by dc42** [comment]
Please re-test this using firmware 1.21.3.

**Comment by timmit99** [comment]
Unfortunately the firmware does not fix this issue.
On the Print page it looks fine but the Control page still has this issue. This is the same as on the 1.20beta4 firmware running on our other screen

![20180613_132221](https://user-images.githubusercontent.com/8399317/41367622-911d0db0-6f0d-11e8-9d94-dd2c347f597c.jpg)
![20180613_132224](https://user-images.githubusercontent.com/8399317/41367623-913034e4-6f0d-11e8-9131-4f5180c3ea57.jpg)

**Comment by apphead** [comment]
Again, that is not even alpha release kind of issues. See https://github.com/dc42/PanelDueFirmware/issues/39#issuecomment-566737281

**Comment by wilriker** [comment]
This has been fixed in 3.2-RC2.

**Comment by wilriker** [comment]
Please reopen if it is not working for you.
