### ISSUE TITLE
M291 S3 message not cleared

### ISSUE THREAD

**Issue by dc42** [Duet3D/PanelDueFirmware#239]
### Description

If a macro is invoked from PanelDue, and that macro used M291 S3 to display a message requiring an acknowledgement, and that message is acknowledged in DWC, then the message is not cleared in PanelDue until the macro terminates.

To reproduce:
1. Put the following commands in a macro file:
M291 S3 P"S3 message"
G4 S20
2. Start the macro from PanelDue
3. Press OK in the message box displayed in DWC.

The fix involves both RRF and PanelDueFirmware. The change needed in PanelDueFirmware is that if in the object model response received field state.messageBox is present with value null then PanelDue should close the message box and revert to the "no message x" active state. Note, the existing PanelDue JSON parsing code replaces a null value with an empty string.

**Comment by mfs12** [comment]
Sending "null" message box clear the message properly.
