### ISSUE TITLE
Firmware 3.4.0 Release

### ISSUE THREAD

**Issue by mikerocklewitz** [Duet3D/PanelDueFirmware#241]
### Description

In the releases page, it is stated that paneldue firmware 3.4.0 (latest) requires rrf 3.3 or later.

That is contradictory to all the prior beta releases requiring rrf 3.4 or later.

Does the new 3.4.0 paneldue release work with rrf 3.3 or is that a typo?

**Comment by mfs12** [comment]
@mikerocklewitz thanks for pointing to it. But yes it's intentional as it is really compatible with RRF-3.3.

There's no real need for the version matching scheme.
