### ISSUE TITLE
Add switch to disable status logging

### ISSUE THREAD

**Issue by Modix3D** [Duet3D/PanelDueFirmware#279]
## Description
Very frequent info: status changed messages. These don't add any useful information, but can clog the PanelDue config

https://forum.duet3d.com/topic/29951/paneldue-getting-frequent-info-popups-clogging-the-console

## Versions
Paneldue version 3.4.1, ReprapFirmware 3.4.2

## Process
Happens on any bootup or use of the printer. Especially if there is a less than ideal WiFi setup

## Experienced Result
Very frequent info: status changed messages. These don't add any useful information, but can clog the PanelDue config
![Screenshot 2022-11-21 111319](https://user-images.githubusercontent.com/103570996/203089032-c86e101c-cf7a-4b3f-9bce-c8ab1520d874.png)

## Expected Result
Info: status messages being either disabled, or able to set them using a variable. Useful for debugging, but not for day-to-day use.

**Comment by dc42** [comment]
I suggest we generalise this to a switch for Normal/Verbose status messages, because in future we may wish to add additional message in verbose mode. The default shood be Normal.

**Comment by mfs12** [comment]
Added toggle switch to setup up page. Setting is stored in nvram.
