### ISSUE TITLE
Display Baby Stepping option at all times

### ISSUE THREAD

**Issue by droftarts** [Duet3D/PanelDueFirmware#301]
### Description

Using RRF 3.5beta2, PanelDue firmware 3.4.1, Baby stepping is only displayed during printing.

The 'Baby stepping' button on the 'Status' screen should be displayed all the time, to allow manual adjustments before starting a job. Please swap the positions of the 'Pause' button (which only displays during printing/simulation) and 'Baby step' button, so that it can be available permanently.

Currently it only displays when a job or simulation is running, though this does not seem to be entirely consistent.
David tested behaviour: 

> On my PD I only see the babystepping option when a job is in progress
> I've just started a short job and left the babystepping popup displayed. I expect it will still be there when the job finished. I'll let you know.
> yes, the popup is still there even though the status has changed to Idle.

Tony agreed it should be available all the time.
This may be related to this previously closed issue: https://github.com/Duet3D/PanelDueFirmware/issues/267

**Comment by mfs12** [comment]
If printer gets paused and then resumed, the UI toolkit uses the cancel button instead. therefore cancel button needs to be disabled when the printer is paused.
