### ISSUE TITLE
Increase Size of Tiles on PanelDue

### ISSUE THREAD

**Issue by wschadow** [Duet3D/PanelDueFirmware#314]
### Description

I'm glad that my feature request regarding multiple choices and even input of text and values got implemeted! That's a big plus, thank you so much!!

The displayed message in DWC looks good, but on PanelDue the tiles could be a bit bigger to display more information (maybe 12 characters at most).

![IMG_2674](https://github.com/Duet3D/PanelDueFirmware/assets/25696872/02a4f99d-1009-438e-9a2b-385a6970b7a4)

There is a bug as well: with the option J1 the "Cancel" tile is not displayed on the PanelDue

It's displayed correctly on DWC

![image](https://github.com/Duet3D/PanelDueFirmware/assets/25696872/2aaa6c0e-5879-4018-a8e5-1b7ecffdfdd3)

**Comment by mfs12** [comment]
Hey @wschadow, after talking to the team. We do not plan to fix this. Closing it.
