### ISSUE TITLE
Cancel buttton with M292 J1 not displayed on PanelDue

### ISSUE THREAD

**Issue by wschadow** [Duet3D/PanelDueFirmware#315]
### Description

It' tested with PanelDue Firmware 3.5.0-rc7  and 3.5.0 Release Candidate 1
The command

`M291 j1 R"Preheat extruder for" P"Select one material or press CANCEL." S4 K{"PLA (210°C)","PETG(235°C)", "ABS (260°C)","PLA (210°C)","PETG(235°C)", "ABS (260°C)"} ; Display user prompt`

is not displayed correctly on the PanelDue (Cancel is missing):

![IMG_2674](https://github.com/Duet3D/PanelDueFirmware/assets/25696872/02a4f99d-1009-438e-9a2b-385a6970b7a4)

It's displayed correctly on DWC

![image](https://github.com/Duet3D/PanelDueFirmware/assets/25696872/2aaa6c0e-5879-4018-a8e5-1b7ecffdfdd3)

**Comment by mfs12** [comment]
The cancel button was added with the rrf-3.5 specification.
