### ISSUE TITLE
Two digits for the display of x and y coordinates

### ISSUE THREAD

**Issue by wschadow** [Duet3D/PanelDueFirmware#317]
### Description

The x and y coordinated are displayed with one digit:

![image](https://github.com/Duet3D/PanelDueFirmware/assets/25696872/06292d36-74f2-4883-9af0-e35b65f774c0)

Especially for the calibration of an IDEX machine it would be very helpful if two digits would be shown.

**Comment by mfs12** [comment]
Hey @wschadow, do you request those two digits for DuetWebControl or PanelDue? This is a bit unclear.

If PanelDue please share the right screenshot, if DuetWebControl then this issue needs to be moved to DuetWebControl project.

**Comment by wschadow** [comment]
Sorry for the confusion, I meant both but submitted the wrong screenshot. I just created a pull request for the changes in the PanelDue firmware. 

Thanks for fixing the display of the buttons already!

**Comment by mfs12** [comment]
Needs to be reverted as support for values up to 999 are necessary.
