### ISSUE TITLE
No Macros or Gcodes with Duet 3 MB6HC, SBC w/DuetPi Bookworm, RRF 3.5.1

### ISSUE THREAD

**Issue by blt3dp** [Duet3D/PanelDueFirmware#334]
### Description

Before posting a bug report here, please check the forum and gitlab issue tracker if it was already reported.

- https://forum.duet3d.com/category/14/paneldue
- https://github.com/Duet3D/PanelDueFirmware/issues

If you need help configuring your device please visit the forum and post your questions there.

## Description
PanelDue 7i shows no Macros or Gcodes with Duet 3 MB6HC, SBC w/DuetPi Bookworm, RRF 3.5.1

## Versions
Duet 3 MB6HC, SBC w/DuetPi Bookworm, RRF 3.5.1
PanelDue 7i, originally firmware 3.4.1-pre2, updated to 3.5.0-rc8

## Process
Tap SD card button on main screen and it reports no gcodes found
Macros are not showing in upper right corner
Tap macros button and it reports no macros found

## Experienced Result
Reports no gcodes or macros found

## Expected Result
Macros show on the home screen as before
Tapping either the SD card or Macros button displays either gcodes or Macros

**Comment by dc42** [comment]
Closing due to no response from originator.
