### ISSUE TITLE
Macros that uses M291 with jog buttons only work where it was startarted (DWI or PanelDue)

### ISSUE THREAD

**Issue by brunofporto** [Duet3D/PanelDueFirmware#34]
If I start the macro at DWI it only works from DWI. If I start the macro from PanelDue it only works from PanelDue. Also the messages sent to the console, in this case G30 S-1 reports, only shows at the respective console (DWI if started from DWI, PanelDue if started from Panel Due).

**Comment by dc42** [comment]
This is the intended behaviour. Responses to commands are sent to the channel that the command came from. Error messages and responses to commands in a gcode file that is being printed are sent to all active channels.

**Comment by wilriker** [comment]
Closing since this is intended behavior.
