### ISSUE TITLE
About adding new language

### ISSUE THREAD

**Issue by crazyp1g** [Duet3D/PanelDueFirmware#38]
I want to add new languages to PanelDue language support, because my native language is Chinese, and I did so, but the result is and I imagine the different, all the Chinese characters are displayed on the screen to black squares, I checked some data speculation because font directory no corresponding word stock, but can you tell me how to do?

**Comment by wilriker** [comment]
You would need to use https://www.mikroe.com/glcd-font-creator to create a new font that contains the required symbols.

**Comment by wilriker** [comment]
Closing this one. Please open a thread in the forum if you need further assistance.
