### ISSUE TITLE
Configurable UI

### ISSUE THREAD

**Issue by Patrik-svobodik** [Duet3D/PanelDueFirmware#47]
Hi, this might be hard but it would be very appreciated. I would love to be able to configure the UI of PanelDue the same way as you can with the 12864LCD, the PanelDue would load the file and read it and render the UI, it could use the standard components, nothing wrong with that

**Comment by mfs12** [comment]
@Patrik-svobodik the software would need a major overhaul for that. And this is not very likely to happen. Therefore I am closing this issue.
