### ISSUE TITLE
Backlights and Use USB to flash the firmware

### ISSUE THREAD

**Issue by Laiwxn** [Duet3D/PanelDueFirmware#6]
Hi,David.
1.However I touch the Setup>Backlights- or Backlights+,The backlights isn't change anymore.
2.The PanelDue can't flash the firmware through the USB interface.I connent the Board to the PC with a microUSB co,but there was nothing happen on the PC.I am sure that the cable is good,and I can use the USB to flash the firmware of the Duet Board.So I must flash the firmware through the SWD Interface.

**Comment by dc42** [comment]
Did you resolve this? Which version PanelDue controller board do you have?

**Comment by wilriker** [comment]
Closing since this is rather a hardware issue.
