### ISSUE TITLE
PanelDue firmware Release 1.23.2 Issue with "Idle" "Busy" indicator

### ISSUE THREAD

**Issue by wkellyoconnor** [Duet3D/PanelDueFirmware#61]
I upgraded my 4.3" version 3 PanelDue's Firmware to Release 1.23.2, file: "PanelDue-v3-4.3.bin" and found this issue: When I press the "Home All" button on the PanelDue, the action begins but the "Idle" indicator never changes to "Busy" during the operation. After homing, I can press X, Y, X move buttons and after each press, the "Idle" Changes to "Busy" right away. If I run a homing action from DWC the PanelDue will show "Busy" just fine. Re-running the "Home All" operation from the PanelDue never changes from "Idle" to "Busy"

**Comment by wilriker** [comment]
This is actually a limitation in RepRapFirmware not sending out status responses when being busy on the same channel.

I close this since a change to this behavior is currently under review.
