### ISSUE TITLE
Display not refreshing correctly

### ISSUE THREAD

**Issue by JPluess** [Duet3D/PanelDueFirmware#62]
This issue is persistent and i use a PanelDue V3.0 
I have a dual Z-Axis and the Z2 -> U Axis, is not being hidden properly after homing. 

Here is a photo of the issue:

![a4a2ba31-f071-44b5-b8aa-e5f1e15aaac2](https://user-images.githubusercontent.com/7995240/74986670-cdbff580-5439-11ea-820c-ad9b316cd509.jpg)

thanks a lot, good work.

**Comment by wilriker** [comment]
This should be working on 3.2-RC2.

**Comment by wilriker** [comment]
Please reopen if it is not working for you.
