### ISSUE TITLE
No Bed Heater, But Do Have Chamber Heater?

### ISSUE THREAD

**Issue by ajquick** [Duet3D/PanelDueFirmware#66]
Kind of an oddball setup, I know.

I have no bed heater (M140 H-1), but do have a chamber heater (M141 H0).

Is there any way to get Chamber heater to be displayed on the PanelDue? Is it possible to not display the Bed heater if its disabled?

My work around is to just have the chamber heater assigned to the bed heater, that way it shows up on the Paneldue, but then my online interface calls the Chamber heater "Bed", which is annoying.

**Comment by wilriker** [comment]
This has been implemented in 3.2-RC2.

**Comment by wilriker** [comment]
Please reopen if it is not working for you.
