### ISSUE TITLE
Feature Request: Display Heightmap on PanelDue

### ISSUE THREAD

**Issue by flclkrazy** [Duet3D/PanelDueFirmware#69]
My mom added a PanelDue to her Duet 2 Wifi recently and likes the screen so far. One thing the web browser has that the PanelDue doesn't, is the ability to look at the bed's height map. My guess is that it would be to complicated to implement, but could the values be displayed in a chart instead?

**Comment by wilriker** [comment]
Unfortunately since there is no interface on the serial line to fetch the heightmap it is not possible.

I close this now. If you still would like to see this feature, please open a thread over on the forum because this requires coordination across the various components involved.
