### ISSUE TITLE
Feature Request: Heater - Active vs. Standby Indication

### ISSUE THREAD

**Issue by presto87** [Duet3D/PanelDueFirmware#70]
Please improve the heater icons to better differentiate between "Active" and "Standby" status on the PanelDue display.

A couple ideas to do this:
1. Change heater icon color based on status (Green = Active) / (Yellow = Standby)
2. Change Active/Standby setpoint displays to show which value is being used, with either colored background, or bold text when in use.

**Comment by wilriker** [comment]
This has been implemented in 3.2-RC2.

**Comment by wilriker** [comment]
Please reopen if it is not working for you.
