### ISSUE TITLE
3.2 RC2 changing extrusion % gives M221 D parameter to high

### ISSUE THREAD

**Issue by KipK** [Duet3D/PanelDueFirmware#75]
sw: Reprap 3.2 beta 1, paneldue 3.2 RC2
hw: Duet 2 Wifi, Paneldue7

Changing extrusion flowrate from panel due throw an error in the console:
M221 D parameter to high

Parameter stays changed in paneldue, but duet not.

**Comment by wilriker** [comment]
I found and fixed the issue. Thanks for reporting. This will be fixed in 3.2-RC3.

**Comment by wilriker** [comment]
I close this issue now. Please reopen if it does not work for you.
