### ISSUE TITLE
3.2 RC2 Time Left not automatically refreshing

### ISSUE THREAD

**Issue by dang472** [Duet3D/PanelDueFirmware#76]
While printing, the time left paramaters are not automatically refreshing. If I click to anothe rpage and then back it rereshes.

**Comment by wilriker** [comment]
Thanks for reporting. I have an idea what could cause this. I'll check that.

**Comment by wilriker** [comment]
This will be fixed in the next release.

**Comment by wilriker** [comment]
I will close this now. Please reopen if this happens again in 3.2-RC3 (to be released).
