### ISSUE TITLE
Add Firmware Erase Button in UI

### ISSUE THREAD

**Issue by wilriker** [Duet3D/PanelDueFirmware#79]
In some cases it is hard to reach the physical erase and reset buttons and thus a touch button in firmware should be added to erase flash and reset the controller such that it is ready to be flashed.

**Comment by wilriker** [comment]
This can be done now via RepRapFirmware by sending
```
M999 A1 P"ERASE"
```
There will be no button added to PanelDueFirmware.

**Comment by mfs12** [comment]
Wrong milestone was set.
