### ISSUE TITLE
Modernisation with LVGL

### ISSUE THREAD

**Issue by JPluess** [Duet3D/PanelDueFirmware#82]
Hi there

I stumbled  upon LVGL...

LVGL is an open-source graphics library providing everything you need to create embedded GUI with easy-to-use graphical elements, beautiful visual effects and low memory footprint.  

Lvgl.io

Would be nice to see some light animations...

Thanks

**Comment by wilriker** [comment]
Thanks for bringing this to attention. I will have a look at that though I personally would rather not do any animations since they take time and a snappy (but nicer looking) interface take precedence.

**Comment by mfs12** [comment]
# LVGL 

- https://lvgl.io/features
- 16,32 or 64 bit microcontroller or processor
- 16 MHz speed is recommended
- Flash/ROM: > 64 kB (180 kB is recommended)
- RAM: 8 kB (24 kB is recommended)
- 1 Frame buffer: in MCU, external RAM, or display controller

**Comment by mfs12** [comment]
Version 3 along with 5i v1 and 7i v1

ATSAM4S4B processor, 120MHz, 64kB RAM, 256kb flash.
Version 2 manufactured from August 2016

ATSAM3S4B processor (64MHz, 48kb RAM, 256kb flash).
Version 1.0, 1.1 and earlier 2

ATSAM3S2B processor (64MHz, 32kb RAM, 128kB flash)

**Comment by dc42** [comment]
The current PanelDue hardware has insufficient memory to run LVGL, however we plan to use LVGL or another framework when we migrate PanelDue to more powerful hardware.

**Comment by T3P3** [comment]
A switch to LVGL would be a different hardware and screen firmware, if done.
