### ISSUE TITLE
Fan showing an incorrect value

### ISSUE THREAD

**Issue by garyd9** [Duet3D/PanelDueFirmware#89]
For full details on what/why, please see "https://forum.duet3d.com/topic/20842/paneldue-3-2-7-bug-with-fan-reporting"

I'm going to guess that the quick fix for this would be to change PanelDue.cpp around line 446:

Replace: { rcvFansActualValue,				"fans^:actualValue" }
with: { rcvFansActualValue,				"fans^:requestedValue" }

**Comment by wilriker** [comment]
This will be fixed in the next release.
