### ISSUE TITLE
Changing idle heater active temp does not show until activated again

### ISSUE THREAD

**Issue by Alex9779** [Duet3D/PanelDueFirmware#9]
When I change the active temperature of a currently inactive heater I see the new temperature for about 2 seconds after accepting, then the display reverts to the previous value.
But the value seems to be set because when the heater then gets active the new temperature is used and also displayed.

**Comment by dc42** [comment]
Alex, did you close this because it is resolved now?

**Comment by Alex9779** [comment]
Ummm no, actually I didnt test after I updated the panel a few weeks ago, I just cleaned my open and ancient issues...

**Comment by Alex9779** [comment]
Ok tested it, actually it is not solved, important is that an other heater has to be active, then setting the temperatures of an inactive heater has that issue...

**Comment by wilriker** [comment]
This should be fixed in 3.2-RC2. Can you retest with that one?

**Comment by wilriker** [comment]
Please reopen if it is not working for you.
