### ISSUE TITLE
2nd chamber heater on LCD switches 1st heater

### ISSUE THREAD

**Issue by dvmourik** [Duet3D/PanelDueFirmware#90]
We have 2 chambers / heaters with sensors.
In the web interface everything works as it should. We can switch Chamber Heater 1 and 2 without any problem.
When we try to switch on the Chamber Heater 2 on the LCD screen heater 1 turns red.
When we do it on the console with M141 P1 S60 it does switch the right heater.

Looks like the P1 isn't set in the button?

**Comment by wilriker** [comment]
Thanks for reporting. I found the issue and will fix it with the next version.

**Comment by wilriker** [comment]
This was fixed in 3.2.8.
