### ISSUE TITLE
PanelDue 7I colour issue

### ISSUE THREAD

**Issue by RootCNC** [Duet3D/PanelDueFirmware#93]
Hi everyone,

I've recently purchased a Duet 3 6HC and a PanelDue 7i from Ooznest (Literally two days old) and been updating the files etc of the Rapsberry Pi, Duet and the LCD

However, updating to the latest version Release 3.2.9 I get these results: please help.
![image](https://user-images.githubusercontent.com/26190613/105077308-3ff2ed00-5a84-11eb-9e35-bf01711703fa.png)

I've attempted to use load the following with the same effect:

- PanelDueFirmware-v3-7.0-nologo.zip
- PanelDueFirmware-v3-7.0.zip
- PanelDueFirmware-v3-7.0C-nologo.zip

I did double check and the IC is the ATSAM4S4B ie V3 from the files list :
![image](https://user-images.githubusercontent.com/26190613/105077267-2d78b380-5a84-11eb-82e8-9c1e749c6df9.png)

The original version that was shipped with the device was 1.23.2 - if that makes any odds 

Any thought?

**Comment by beikeland** [comment]
use the 5i-7i binary

**Comment by RootCNC** [comment]
Wheeeeyyyyyy Back in business! thank you :)

Apparently I'm as blind as a bat! thank you
