### ISSUE TITLE
Control gpio pins of the paneldue via gcode

### ISSUE THREAD

**Issue by wildblue** [Duet3D/PanelDueFirmware#95]
This feature has to be first implemented in the panelduet firmware, to be used further down the line.

When available, please add milestones to the other components.

**Comment by wilriker** [comment]
Sorry for the slow reply. I think about how to implement this idea best.

Out of curiosity, what is your use-case?

**Comment by mfs12** [comment]
Gcodes could then be used to control LEDs and switches.

**Comment by mfs12** [comment]
The available gpios are intended for this use. They will likely be part of a future feature.
